variables:
  GOPRIVATE: "gitlab.com/coreflux-cloud/*"

before_script:
  - git config --global url."git@gitlab.com:".insteadOf "https://gitlab.com/"
  - apt-get update -y && apt-get install -y openssh-client
  - eval $(ssh-agent -s)  # Start the ssh-agent
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  # Add the SSH key
  - mkdir -p ~/.ssh
  - ssh-keyscan gitlab.com >> ~/.ssh/known_hosts
  - chmod -R 700 ~/.ssh
  - chmod 600 ~/.ssh/known_hosts
  - ssh -vT git@gitlab.com
  - go env

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - go.mod
    - go.sum
    - .cache/go-build
    - $GOPATH/pkg/mod
    - cache/

include:
    - template: Security/SAST.gitlab-ci.yml

stages:
    - lint
    - test
    - build

lint:
  stage: lint
  image: golang:1.21.9
  script:
    - go mod tidy
    - make fmt
    - make lint
  cache:
    policy: pull-push

test:     
  stage: test
  image: golang:1.21.9
  script:
    - go mod tidy
    - make test
  cache:
    policy: pull-push

sast:
  stage: test
  before_script: []
  script:
    - /analyzer run

build:
  stage: build
  image: golang:1.21.9
  script:
    - go mod tidy
    - make build
    - |
      if [[ "$CI_COMMIT_REF_NAME" == "main" ]]; then
        export RELEASE_TAG="cfctl-${CI_COMMIT_SHORT_SHA}"
      elif [[ "$CI_COMMIT_REF_NAME" == "dev" ]]; then
        export RELEASE_TAG="cfctl-beta-${CI_COMMIT_SHORT_SHA}"
      fi
    - echo "Release tag set to $RELEASE_TAG"
    - >
      curl --header "PRIVATE-TOKEN: $GITLAB_TOKEN_RELEASE" --upload-file ./cfctl "https://gitlab.com/api/v4/projects/$CI_PROJECT_ID/packages/generic/$RELEASE_TAG/${CI_COMMIT_SHORT_SHA}/binary"
  only:
    - main
    - dev
  cache:
    policy: pull-push

